name: testing
on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main
jobs:
  test-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
    -   name:  Checkout repo
        uses: actions/checkout@v3
    -   uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: 2.2.1
    -   name: Install dependencies
        run: |
          pdm install --dev
    -   name: Lint with flake8
        run: |
          pdm run nox -s lint-${{ matrix.python-version }}
    -   name: Type-check with mypy
        run: |
          pdm run nox -s mypy-${{ matrix.python-version }}
    -   name: Execute tests
        run: |
          pdm run nox -s test-${{ matrix.python-version }}
